spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billbook_db
    username: billbook
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: junyeon03@gmail.com
    password: zqpltgnkfihsjifo
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 배포는 none 추천
    show-sql: true       # 콘솔에 SQL 로그 출력
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Optional: 서버 포트 변경 시
  # server:
  #   port: 8081
